### ISSUE TITLE
MapShed Workflow: Update Front-End Code

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1298]
Following #1296 and #1297, we will have two endpoints: one to run the MapShed GIS chain for the project, and another to run the GWLF-E model for the scenario. Update the controllers / task runners in the front-end JavaScript code to implement the following interaction model:

 * [x] When the user creates a new project, we trigger a MapShed GIS chain, and poll until it completes #1310 
 * [x] Once the MapShed GIS chain completes, we trigger a GWLF-E model run for Current Conditions (with no special properties) and New Scenario (also with no special properties at first), and poll until it completes #1310 
 * [x] Once the MapShed GIS chain completes, we inspect the output to retrieve properties used to fill in Land Use percent, other quantities #1314 
 * [x] Once the GWLF-E model run completes, ~~we query the database for~~ it should return results of the model run and populate the charts and tables. These results should also be saved to the database so that when the scenario is re-loaded they load instantly. #1329 

Consider adding error handling and retry options for when any of the steps above fail.

**Comment by lewfish** [comment]
> Once the GWLF-E model run completes, we query the database for results of the model run and populate the charts and tables

I'm a little confused by the above statement. The backend should respond with the results on the final poll, so there shouldn't be a separate query for the results.

**Comment by rajadain** [comment]
Good point. The backend should respond with the results, in addition to saving them to the database. When re-loading a saved scenario, we can probably check if the results are already populated or not before running them again, a-la TR-55.

**Comment by rajadain** [comment]
Updated the description to reflect. Feel free to further edit it to fit.

**Comment by rajadain** [comment]
Originally 8 points, -3 to #1310

**Comment by rajadain** [comment]
-2 to #1327

**Comment by lewfish** [comment]
- [ ] Show x% of length or area in manual entry UI
- [ ] Disable thumbnails for BMPs that can't really be applied to the AOI

**Comment by lewfish** [comment]
-1 to #1338

**Comment by lewfish** [comment]
-1 te #1343

**Comment by rajadain** [comment]
-1 to #1345
