### ISSUE TITLE
Geoprocessing API: Add Shape Validation

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2186]
Currently the front end does most of the shape validation though there is some backend validation. Ensure the api checks that:
- [ ] ~the shape is in the CONUS~ #2340
- [ ] ~The projection is correct~ #2341
- [ ] ~Shape does not self intersect~ #2342
- [ ] ~Size~ #2342

- [ ] ~For rwd, add validators for required keys (`location`)~ #2344

**Comment by arottersman** [comment]
Broke this off into separate cards.
