### ISSUE TITLE
MMW OSI Feedback Blackbox

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3259]
Initially :two: points.

- [x] The raw value of precipitation in the Weather Station pop-up is in millimeters, not inches. Make it respect the user's unit preferences.
- [x] Add a link to technical documentation for Weather Stations ~~to be provided by Dave Arscott~~ https://wikiwatershed.org/help/model-help/mmw-tech/#usepa-climate
- [x] Following up from #3254 and #3261, still seeing repeating numbers for Little Neshaminy Creek:
    ![image](https://user-images.githubusercontent.com/1430060/75700470-1c626080-5c80-11ea-8310-e3faa7be3db1.png)
- [x] Fix Mapbox attribution in main basemap https://docs.mapbox.com/help/how-mapbox-works/attribution/
- [x] Following up from #3245 and #3257, make it so that when a saved MapShed project is reloaded, the active weather stations are set correctly
  - Also ensure that it doesn't crash for earlier saved MapShed projects that won't have a `WeatherStations` key in their `gis_data`
- [x] Following up from #3245 and #3257, make it so that deleting a project unsets active weather stations
