### ISSUE TITLE
OSI Custom Weather Data Upload

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3267]
* [x] Finalize CSV Format #3268
* [x] Add Boto3, Django Storages for S3 Uploads #3274
* [x] ~Add Django Model, Migrations #3269~
* [x] Rewrite Modal, Migrations to associate with Scenarios #3296
* [x] ~Add Serializer, Endpoint for Upload #3270~
* [x] Rewrite Serializer, Endpoint to associate with Scenarios #3297
* [x] Add Endpoint to Download Weather Data #3271
* [x] Talk to design and figure out where the custom upload dialog will be triggered from
* [x] ~Add Button to Open Upload Dialog #3272~
* [x] Rewrite button to associate with Scenarios #3298
* [x] Add the dialog itself to the ui #3287
    - [x] Talk to copywriting to write instructions on how to use this feature
    - [x] Allow for file uploads
    - [x] Add link to download sample CSV
* [x] Send the uploaded file with relevant information (project, scenario, user IDs) to the new upload endpoint #3287 
* [x] Perform validation in the endpoint and report back any errors #3284 
    - [x] Show validation errors in the ui #3288
* [x] Incorporate the new weather data in MapShed #3289
* [x] Save the uploaded data to ~the database~ S3 and inform the client, so it can trigger a recalculation with the new uploaded data #3290
* [x] Add ui to see what data was uploaded and have it be re-exportable #3287 
    - [ ] Consider doing this for default climate data (and future climate predictions) as well #3271 
* [x] Add uploaded climate data to HydroShare Exports

**Comment by rajadain** [comment]
Originally 8️⃣ points

**Comment by rajadain** [comment]
- 1️⃣ to #3268

**Comment by rajadain** [comment]
Now  0️⃣  points

**Comment by rajadain** [comment]
Closing as this work is now complete.
